backend: 
  name: git-gateway
  repo: BlessingOkonkwo/DevCareer-Blog
  branch: cms
media_folder: public/img
public_folder: img
collections: 
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - label: 'Posts'
            name: 'posts'
            widget: list
            fields:
            - { label: "Author", name: "author", widget: "string" }
            - { label: "Date", name: "date", widget: "datetime" }
            - { label: "Article Title", name: "article_title", widget: "string" }
            - { label: "Article Description", name: "article_description", widget: "markdown" }