backend:
  name: git-gateway
  repo: Qaasim-Umar/DevCareer-blog-page
  branch: main

publish_mode: editorial_workflow

media_folder: public/img
public_folder: /img

collections:
  - name: "pages"
    label: "pages[[p-l]]"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - label: "Posts"
            name: "posts"
            widget: list
            fields:
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - {
                  label: "Article Title",
                  name: "article_title",
                  widget: "string",
                }
              - {
                  label: "Article Description",
                  name: "article_description",
                  widget: "markdown",
                }


    folder: "pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

